name: Build and deploy Node.js project to Azure Function App - func-frema-dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  # CI では husky を無効化
  HUSKY: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 念のため git hooks も無効化（HUSKY=0 と併用）
      - name: Disable git hooks on CI
        run: git config --global core.hooksPath /dev/null

      # pnpm は packageManager のバージョンと合わせる（例: 9.7.0）
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile || pnpm install

      # Functions パッケージをビルド
      - name: Build functions
        run: pnpm -r --filter "./apps/functions" build

      # ★ 自己完結の配布物を作成（host.json / dist / node_modules を同梱）
      - name: Make deploy bundle (pnpm deploy)
        run: |
          rm -rf functions_bundle
          pnpm --filter "./apps/functions" deploy --prod --out-dir functions_bundle
          test -f functions_bundle/host.json

      - name: Upload artifact (functions bundle)
        uses: actions/upload-artifact@v4
        with:
          name: functions
          path: functions_bundle

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functions
          path: ./functions_artifact

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_886AA54188164EA4A815A3018D07D6BC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A92E72DFDD0A4A45AD361F41A0FCC47A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6DE080F944D046B7BFE6C04F57533B43 }}

      # Azure Functions へのデプロイ（v1 を使用）
      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: func-frema-dev
          package: ./functions_artifact
          respect-funcignore: true
